### PR TITLE
Design change inputs

### PR DESCRIPTION
**Pull request by rodriguez-facundo**
Contains changes to layout for cellParams and inputParams

### CODE REVIEW

**Review by tarelli — COMMENTED** [review]
@rodriguez-facundo The main problem I have with this is how we duplicated the NetPyNE model interpreter

**Comment by rodriguez-facundo** [comment]
can you elaborate on that @tarelli? The interpreter is an exact copy of geppetto-netpyne interpreter. Were you expecting something different?

**Comment by tarelli** [comment]
@rodriguez-facundo yes I didn't mean we didn't copy it well, by that we duplicated the code and now it exists in two separate independent codebases. We should either have NetPyNE-UI as a python dependency and we reuse the model interpreter from that or factor it out to another repo and import it in both NetPyNE-UI and HNN-UI. I see downsides in both, maybe the first one is easier. There might be a third option I didn't think about, thoughts?

**Comment by rodriguez-facundo** [comment]
- I'm not a huge fan of the first option because we are getting entangled with NetPyNE-UI and then we have to worry about dependencies and other potential issues (travis-ci). 
- Maybe having it as a pip package would be a nice approach, but it will be yet another pip package to maintain.

Between the two I prefer a pip package.

**Comment by tarelli** [comment]
Yeah those were the downsides I also had in mind. I am also inclined right now to add a new repo and a new pip package.

**Comment by tarelli** [comment]
@rodriguez-facundo FYI merged this for now as the model interpreter was already in. Let's discuss on Monday what to do regarding factoring it out.

**Pull request merged**
